#!/bin/sh

rm -fr /etc/apt/sources.list.d/pardus-yirmiuc.list

SOURCE_LIST=/etc/apt/sources.list

cat > $SOURCE_LIST <<EOF
### Official Pardus ETAP Package Repositories ###

## ETAP
deb http://depo.etap.org.tr/etap yirmiuc main contrib non-free non-free-firmware
# deb-src http://depo.etap.org.tr/etap yirmiuc main contrib non-free non-free-firmware

## Pardus
deb http://depo.etap.org.tr/pardus yirmiuc main contrib non-free non-free-firmware
# deb-src http://depo.etap.org.tr/pardus yirmiuc main contrib non-free non-free-firmware

## Pardus Deb
deb http://depo.etap.org.tr/pardus yirmiuc-deb main contrib non-free non-free-firmware
# deb-src http://depo.etap.org.tr/pardus yirmiuc-deb main contrib non-free non-free-firmware

## Pardus Security Deb
deb http://depo.etap.org.tr/guvenlik yirmiuc-deb main contrib non-free non-free-firmware
# deb-src http://depo.etap.org.tr/guvenlik yirmiuc-deb main contrib non-free non-free-firmware

EOF
